{"uuid": "90a1b16f-ef90-4ee9-962c-90680a02c973", "children": ["5641b86c-6ab9-4373-a10a-c0bc411e03ce"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=75.0.3770.142)\n\n", "trace": "  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"D:\\python\\pageAutoTest\\Testcase\\conftest.py\", line 24, in login\n    WebTools(driver).set_browser(login_url)\n  File \"D:\\python\\pageAutoTest\\Common\\CommonFunc.py\", line 39, in set_browser\n    self.driver.get(testUrl)  # 打开被测系统URL\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\tools\\python3.7.5\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1596608729983, "stop": 1596608737036}], "start": 1596608729983, "stop": 1596608737177}